server: 
    port: 8081
    enviroment: :production
    public_folder: public
    rack_server: :thin

scheduler:
    timer: 600

resources:
  resource_path: layers
  zones: "zones.geojson"
  train_station: "stations.geojson"
  rails: "rails.geojson"
  metro_lines: "metro_lines.geojson"
  metro_stations: "metro_stations.geojson"
  dog_zone: "dog_zone.geojson"
  parks: "parks.geojson"
  bike_parking: "bike_parking.geojson"
  bike_paths: "bike_paths.geojson"
  
